"""File-type handler registry for vault-bridge.



Generated by scripts/generate_file_type_handlers.py — but also usable standalone.

Provides:
  HANDLERS   — dict[str, HandlerConfig] mapping extension → handler config
  get_handler(path) -> HandlerConfig | None
  read_text(path, workdir=None) -> str
  extract_images(path, workdir=None) -> list[Path]
  handle(path, workdir=None) -> HandlerResult

Categories:
  document-pdf      — PDF files (PyPDF2 text + embedded image extraction)
  document-office   — DOCX / PPTX / XLSX (python-docx / python-pptx)
  image-raster      — JPG PNG GIF WEBP BMP TIFF HEIC (Pillow passthrough)
  image-vector      — SVG AI EPS (passthrough; no compression)
  video             — MP4 MOV AVI MKV etc. (skipped — no text/image extraction)
  audio             — MP3 WAV FLAC AAC etc. (skipped)
  text-plain        — TXT MD RST CSV (raw UTF-8 read)
  archive           — ZIP RAR 7Z TAR (skipped)

Delegated categories (v14.3, F1/F6) — dispatched to per-extension handler
modules under `<workdir>/.vault-bridge/handlers/`:
  cad-dxf, cad-dwg, cad-3dm, vector-ai, raster-psd,
  document-office-legacy, spreadsheet-legacy

These are opt-in via /vault-bridge:setup. When the workdir or the handler
file is missing, read_text/extract_images return empty for them rather
than raising — the capability gracefully degrades.

Python 3.9 compatible.
"""
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

import handler_dispatcher

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# HandlerConfig — immutable descriptor per extension category
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class HandlerConfig:
    """Descriptor for how vault-bridge should process a given file category.

    Attributes:
        category:       Slug identifying the file category (e.g. 'document-pdf').
        extract_text:   Whether to attempt text extraction from this file type.
        extract_images: Whether to attempt image extraction / passthrough.
        compress:       Whether to compress extracted images (JPEG, strip EXIF).
        run_vision:     Whether to run LLM vision on extracted images.
        render_pages:   Whether the handler renders pages to images (e.g. DXF, AI, PSD).
    """
    category: str
    extract_text: bool
    extract_images: bool
    compress: bool
    run_vision: bool
    render_pages: bool = False


# ---------------------------------------------------------------------------
# HANDLERS registry
# ---------------------------------------------------------------------------

# Each category's config — defined once and shared across all extensions in
# that category to avoid duplication.
_PDF = HandlerConfig(
    category="document-pdf",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
)
_OFFICE = HandlerConfig(
    category="document-office",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=False,
)
_RASTER = HandlerConfig(
    category="image-raster",
    extract_text=False,
    extract_images=True,
    compress=True,
    run_vision=True,
)
_VECTOR = HandlerConfig(
    category="image-vector",
    extract_text=False,
    extract_images=True,
    compress=False,
    run_vision=False,
)
_VIDEO = HandlerConfig(
    category="video",
    extract_text=False,
    extract_images=False,
    compress=False,
    run_vision=False,
)
_AUDIO = HandlerConfig(
    category="audio",
    extract_text=False,
    extract_images=False,
    compress=False,
    run_vision=False,
)
_TEXT = HandlerConfig(
    category="text-plain",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
)
_ARCHIVE = HandlerConfig(
    category="archive",
    extract_text=False,
    extract_images=False,
    compress=False,
    run_vision=False,
)

# ---------------------------------------------------------------------------
# Visual/CAD handler configs
# ---------------------------------------------------------------------------

_OFFICE_LEGACY = HandlerConfig(
    category="document-office-legacy",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

_SPREADSHEET_LEGACY = HandlerConfig(
    category="spreadsheet-legacy",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

_CAD_DXF = HandlerConfig(
    category="cad-dxf",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=True,
)

_CAD_DWG = HandlerConfig(
    category="cad-dwg",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=True,
)

_VECTOR_AI = HandlerConfig(
    category="vector-ai",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=True,
)

_RASTER_PSD = HandlerConfig(
    category="raster-psd",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=True,
)

_CAD_3DM = HandlerConfig(
    category="cad-3dm",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

# v16.4.0 (AUDIT-5) — SketchUp .skp. SketchUp's binary format is
# closed; the only first-class reader is SketchUp's own SDK (C++,
# requires a desktop install). The stub handler probes for an
# optional `skp2obj` / `skp2unity` CLI; when neither is present it
# emits a metadata-only summary (size, mtime) and surfaces a
# warning so the user can install a converter or skip the file
# rather than silently get "unknown file type".
_CAD_SKP = HandlerConfig(
    category="cad-skp",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

# v16.9.0 (TLS Ask 4) — Adobe InDesign documents.
# .indd is a closed binary format with an embedded JFIF preview;
# .idml is a zip of XML stories that we can text-extract via
# stdlib. The 2026-05-04 TLS field report flagged 2 INDD files
# silently dropped as "unknown file type"; this category closes
# that gap with a delegated handler that emits at minimum a
# JFIF preview + metadata summary.
_DESIGN_INDD = HandlerConfig(
    category="design-indd",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=False,
)

# v16.9.0 (TLS Ask 13) — Sketch (.sketch) and Figma export (.fig)
# metadata-only stubs. Both are closed/proprietary; the handler
# emits a metadata summary so the file doesn't silently fall
# through as "unknown file type".
_DESIGN_SKETCH = HandlerConfig(
    category="design-sketch",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

_DESIGN_FIGMA = HandlerConfig(
    category="design-figma",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

# v16.10.0 (TLS round 3 Ask 2) — Grasshopper definitions.
# .gh is McNeel's proprietary binary format (GH_Document via
# GH_IO.dll). Pure-Python decode of the full graph isn't possible
# without the .NET runtime; the handler does Level 0 (metadata) +
# Level 1 (UUID-shaped block scan + length-prefixed string
# heuristic) so the operator at least sees component complexity
# and any embedded cluster names.
# .ghx is the older XML variant — fully readable via stdlib
# ElementTree; the same handler routes by suffix.
_CAD_GRASSHOPPER = HandlerConfig(
    category="cad-grasshopper",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

# v16.11.0 (FGE Ask 1) — OFD (Open Fixed-layout Document, GB/T
# 33190-2016). China's nationally standardised document format,
# analogous to PDF. Used for invoices, contracts, tax documents,
# government forms — every Chinese enterprise archive carries
# them. The handler walks the OFD zip's Doc_0/.../Content.xml
# and concatenates ``<ofd:TextCode>`` text. Optionally extracts
# the embedded JFIF preview when present.
_DOCUMENT_OFD = HandlerConfig(
    category="document-ofd",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=False,
)

HANDLERS: Dict[str, HandlerConfig] = {
    # document-pdf
    "pdf": _PDF,
    # document-office (XML formats)
    "docx": _OFFICE,
    "pptx": _OFFICE,
    "xlsx": _OFFICE,
    # document-office-legacy (binary OLE2 formats)
    "doc": _OFFICE_LEGACY,
    "ppt": _OFFICE_LEGACY,
    # spreadsheet-legacy (binary XLS)
    "xls": _SPREADSHEET_LEGACY,
    # image-raster
    "jpg": _RASTER,
    "jpeg": _RASTER,
    "png": _RASTER,
    "gif": _RASTER,
    "webp": _RASTER,
    "bmp": _RASTER,
    "tiff": _RASTER,
    "tif": _RASTER,
    "heic": _RASTER,
    "heif": _RASTER,
    # image-vector (SVG/EPS passthrough only; ai now routed to vector-ai)
    "svg": _VECTOR,
    "eps": _VECTOR,
    # vector-ai (Adobe Illustrator via PyMuPDF — renders pages)
    "ai": _VECTOR_AI,
    # raster-psd (Photoshop PSD via psd-tools — composites layers)
    "psd": _RASTER_PSD,
    # cad-dxf (AutoCAD DXF via ezdxf — renders modelspace)
    "dxf": _CAD_DXF,
    # cad-dwg (AutoCAD DWG via ezdxf native reader — renders modelspace)
    "dwg": _CAD_DWG,
    # cad-3dm (Rhino 3DM via rhino3dm — metadata only, no rendering)
    "3dm": _CAD_3DM,
    # cad-skp (SketchUp — metadata-only stub via optional skp2obj CLI)
    "skp": _CAD_SKP,
    # design-indd (Adobe InDesign — JFIF preview + IDML XML text)
    "indd": _DESIGN_INDD,
    "idml": _DESIGN_INDD,
    # design-sketch / design-figma (metadata-only stubs)
    "sketch": _DESIGN_SKETCH,
    "fig": _DESIGN_FIGMA,
    # cad-grasshopper (.gh binary, .ghx XML)
    "gh": _CAD_GRASSHOPPER,
    "ghx": _CAD_GRASSHOPPER,
    # document-ofd (China GB/T 33190-2016 — invoices, contracts)
    "ofd": _DOCUMENT_OFD,
    # video
    "mp4": _VIDEO,
    "mov": _VIDEO,
    "avi": _VIDEO,
    "mkv": _VIDEO,
    "wmv": _VIDEO,
    "m4v": _VIDEO,
    "webm": _VIDEO,
    # audio
    "mp3": _AUDIO,
    "wav": _AUDIO,
    "flac": _AUDIO,
    "aac": _AUDIO,
    "ogg": _AUDIO,
    "m4a": _AUDIO,
    # text-plain
    "txt": _TEXT,
    "md": _TEXT,
    "rst": _TEXT,
    "csv": _TEXT,
    # RTF — v16.4.0 (AUDIT-4). striprtf is the reader; soffice is the
    # fallback when striprtf is absent.
    "rtf": _TEXT,
    # v16.11.0 (FGE Asks 9 + 10) — additional plain-text formats that
    # were silently dropping as ``unknown file type`` despite being
    # readable as raw UTF-8/ASCII.
    "url": _TEXT,      # Windows Internet Shortcut (.ini-style key=value)
    "webloc": _TEXT,   # macOS web-shortcut plist (XML; readable as text)
    "log": _TEXT,      # plain text log files
    "tm": _TEXT,       # TextMate document (plain UTF-8)
    # archive
    "zip": _ARCHIVE,
    "rar": _ARCHIVE,
    "7z": _ARCHIVE,
    "tar": _ARCHIVE,
}


# ---------------------------------------------------------------------------
# HandlerResult — output of handle()
# ---------------------------------------------------------------------------

@dataclass
class HandlerResult:
    """Result of processing a single file through handle().

    Attributes:
        text:     Extracted text, or '' if the category doesn't extract text,
                  or None if the file was skipped (unknown extension).
        images:   Extracted / passthrough image paths.
        skipped:  True when the extension is unrecognised or path is empty.
        category: The category slug from HandlerConfig, or 'unknown' when skipped.
    """
    text: Optional[str] = None
    images: List[Path] = field(default_factory=list)
    skipped: bool = False
    category: str = ""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_handler(path: str) -> Optional[HandlerConfig]:
    """Return the HandlerConfig for the given file path, or None if unrecognised.

    Lookup is by the last extension only (.tar.gz → 'gz').
    Case-insensitive. Leading dot removed.
    Returns None for empty paths, paths with no extension, and dot-files
    with no real extension (e.g. '.hidden').

    v16.6.0 (Batch C8): the registry lookup itself is the validity
    gate — folder basenames like ``210127 v2.3 工地照明 CD`` have a
    last-segment ``rsplit(".", 1)`` of "3 工地照明 CD" which is
    correctly NOT in HANDLERS and therefore returns None. The
    pre-v16.6 issue was that scan-pipeline callers built their own
    ext via naive string-splitting and tried to register it; now the
    canonical check is here. Folder-vs-file dispatch still happens
    in :func:`scan_pipeline.process_file` via ``Path.is_dir()``.

    Args:
        path: File path as string (may be relative or absolute).

    Returns:
        HandlerConfig or None.
    """
    if not path:
        return None

    p = Path(path)
    suffix = p.suffix  # '' or '.ext'
    if not suffix:
        return None

    ext = suffix.lstrip(".").lower()
    if not ext:
        # Dot-file like '.hidden' — suffix is '.hidden', ext is 'hidden'
        # But Path('.hidden').suffix == '' on Python 3.9, so this branch is
        # actually unreachable for dot-files.  Left for clarity.
        return None

    # v16.6.0 (Batch C8): reject "extensions" that don't look like
    # real ones — too long, contain whitespace, contain non-alnum.
    # ``210127 v2.3 工地照明 CD`` would otherwise turn into
    # ext="3 工地照明 cd" which passes ``HANDLERS.get`` (returning
    # None) but pollutes downstream logs as if it were a real ext.
    if not _looks_like_extension(ext):
        return None

    # Dot-file guard: Path('.hidden').stem == '.hidden', .suffix == ''
    # So we only reach here with a real extension.
    return HANDLERS.get(ext)


_EXT_RE = re.compile(r"^[a-z0-9]{1,6}$")


def _looks_like_extension(ext: str) -> bool:
    """Return True when ``ext`` is short, alphanumeric, plausibly a
    file extension. False for free-text-after-dot like
    "3 工地照明 cd". v16.6.0 (Batch C8)."""
    return bool(_EXT_RE.match(ext))


# ---------------------------------------------------------------------------
# Private per-format helpers
# ---------------------------------------------------------------------------

# v16.6.0 (Batch C7) — module-level extraction error registry.
#
# Pre-v16.6 the built-in handlers (PDF, DOCX, PPTX, XLSX) caught every
# library exception and returned ``""``, indistinguishable from a
# legitimately empty file. The 2026-05-04 SSS field report flagged a
# 1-byte-truncated XLSX whose ``BadZipFile`` was masked as
# ``no_content`` — the user could not tell whether the file was
# corrupt, password-protected, or genuinely blank. This registry
# stashes the most recent extraction error per file path so
# ``read_text_with_status`` can surface it. Path-keyed (not thread-
# safe globally — intended for the single-process scan pipeline only).
_EXTRACTION_ERRORS: Dict[str, str] = {}


def _record_extraction_error(path: str, library: str, exc: BaseException) -> None:
    msg = f"{library}: {type(exc).__name__}: {exc}"
    _EXTRACTION_ERRORS[str(path)] = msg


def consume_extraction_error(path: str) -> Optional[str]:
    """Return any recorded extraction error for ``path`` and clear it.

    v16.6.0 (Batch C7). Used by ``read_text_with_status`` to recover
    library exceptions that the built-in handlers swallowed. The
    registry is path-keyed and consumed-on-read so a clean follow-up
    extraction does not see stale errors.
    """
    return _EXTRACTION_ERRORS.pop(str(path), None)


def _pdf_read_text(path: str) -> str:
    """Extract text from a PDF.

    v16.7.0 (TLS Bug 1+5): cascade through pdfplumber → PyMuPDF (fitz)
    → pdfminer.six → PyPDF2 → OCR. Pre-v16.7 the built-in dispatch was
    PyPDF2-only, which produces 4 KB of CMap garbage like
    ``OOb?WÎNa^ú¾èOá`oQl_…`` on Chinese PDFs that use ``/UniGB-UTF16-H``,
    ``/UniCNS-UTF16-H``, or other CID-keyed fonts. The 2026-05-04 TLS
    field report confirmed pdfplumber/fitz/pdfminer all produce clean
    text on the same files; this rewrite makes them the preferred path.

    Design notes:
      * pdfplumber goes first because it handles CJK glyph layout
        better than fitz (per-glyph stripping is acceptable; the
        garble gate later filters the result if extraction quality
        is too low).
      * fitz is second — fast, full Adobe-GB1 / Adobe-Japan1 support.
      * pdfminer.high_level.extract_text is the third try; it is the
        same engine pdfplumber wraps but with different defaults so
        worth retrying when pdfplumber's layout pass mangled glyphs.
      * PyPDF2 stays as a low-priority fallback for back-compat.
        PyPDF2's ``warnings.warn`` calls (``Advanced encoding /UniGB-
        UTF16-H not implemented yet``) are now captured and surfaced
        through the extraction-error registry so they no longer
        disappear into stderr.
      * OCR via pytesseract over PyMuPDF page renders is the final
        fallback for scanned PDFs (v16.5.0, Fix F).

    Each extractor's exception goes through ``_record_extraction_error``
    so ``read_text_with_status`` can surface it as a warning instead of
    silently returning ``""``.
    """
    # v16.13.0 (JAE Finding 0): each extractor's output goes through
    # the CMap-garble gate before being accepted. Pre-v16.13 the
    # cascade returned the first non-empty result, so a CMap-broken
    # pdfminer extract (PUA-saturated unicode soup) short-circuited
    # the entire cascade — the user got 25KB of unreadable text tagged
    # ``content_confidence: high``. The gate forces fall-through to
    # the next extractor when the result is detectably broken.
    import validate_body as _vb

    # 1. pdfplumber — best layout-aware CJK support via pdfminer.six.
    try:
        import pdfplumber  # type: ignore
        with pdfplumber.open(path) as pdf:
            parts = [
                (p.extract_text() or "")
                for p in pdf.pages[:200]
            ]
        text = "\n\n".join(s for s in parts if s.strip())
        if text.strip() and not _vb.is_cmap_garbled_pdf(text):
            return text
    except Exception as exc:
        _record_extraction_error(path, "pdfplumber", exc)
        logger.debug("pdfplumber failed for %s: %s", path, exc)

    # 2. PyMuPDF (fitz) — fast, full Adobe-GB1 support.
    try:
        import fitz  # type: ignore
        doc = fitz.open(path)
        try:
            n = min(len(doc), 200)
            parts = [doc.load_page(i).get_text() for i in range(n)]
        finally:
            doc.close()
        text = "\n\n".join(s for s in parts if s.strip())
        if text.strip() and not _vb.is_cmap_garbled_pdf(text):
            return text
    except Exception as exc:
        _record_extraction_error(path, "PyMuPDF", exc)
        logger.debug("fitz failed for %s: %s", path, exc)

    # 3. pdfminer.six high-level — same engine pdfplumber wraps but
    # with different defaults; sometimes succeeds where pdfplumber's
    # layout pass mangled glyphs.
    try:
        from pdfminer.high_level import extract_text as _pdfminer_text  # type: ignore
        text = _pdfminer_text(path, maxpages=200) or ""
        if text.strip() and not _vb.is_cmap_garbled_pdf(text):
            return text
    except Exception as exc:
        _record_extraction_error(path, "pdfminer.six", exc)
        logger.debug("pdfminer.six failed for %s: %s", path, exc)

    # 4. PyPDF2 — last text extractor (kept for compatibility). Capture
    # any ``warnings.warn`` output (e.g. CMap-not-supported diagnostics)
    # so the extraction-error registry sees them; pre-v16.7 these
    # warnings disappeared into stderr (TLS Bug 5).
    pypdf_text = ""
    pypdf_warnings: List[str] = []
    import warnings as _warnings
    try:
        import PyPDF2  # type: ignore
    except Exception as exc:
        _record_extraction_error(path, "PyPDF2", exc)
        return _pdf_ocr_fallback(path) or ""

    with _warnings.catch_warnings(record=True) as captured:
        _warnings.simplefilter("always")
        try:
            reader = PyPDF2.PdfReader(path)
            parts2: List[str] = []
            for page in reader.pages:
                try:
                    t = page.extract_text()
                    if t:
                        parts2.append(t)
                except Exception:
                    pass
            pypdf_text = "\n".join(parts2).strip()
        except Exception as exc:
            _record_extraction_error(path, "PyPDF2", exc)
            logger.debug("PyPDF2 failed for %s: %s", path, exc)
        for w in captured or []:
            msg = str(w.message)
            pypdf_warnings.append(msg)
            # CJK-CMap diagnostic — surface as a real error so the
            # user knows to install pdfplumber/PyMuPDF for this PDF.
            if (
                "Advanced encoding /Uni" in msg
                or "/UniGB" in msg
                or "/UniCNS" in msg
                or "/UniJIS" in msg
                or "/UniKS" in msg
                or "/Adobe-GB1" in msg
                or "/Adobe-Japan1" in msg
            ):
                _record_extraction_error(
                    path, "PyPDF2",
                    RuntimeError(
                        "CJK CMap not supported by PyPDF2: "
                        + msg
                        + ". Install pdfplumber or PyMuPDF for clean text."
                    ),
                )
                # Drop PyPDF2's CMap-decoded garbage on the floor —
                # pdfplumber already failed, but garbage is worse than
                # nothing because the garble gate downstream may miss
                # short outputs.
                pypdf_text = ""

    # v16.13.0 (JAE Finding 0): even after PyPDF2's own CMap warnings
    # are checked above, the returned bytes can still be PUA garbage
    # if the CMap was partially resolved. Final gate before accepting.
    if len(pypdf_text) >= 50 and not _vb.is_cmap_garbled_pdf(pypdf_text):
        return pypdf_text

    # 5. OCR via pytesseract over PyMuPDF page renders (Fix F).
    ocr_text = _pdf_ocr_fallback(path)
    if ocr_text:
        return ocr_text
    # Last resort: return whatever PyPDF2 produced (may be empty or
    # short) so callers can decide.
    return pypdf_text  # may be empty


def _pdf_ocr_fallback(path: str) -> str:
    """Run pytesseract over PDF page renders.

    Returns ``""`` if pytesseract or PyMuPDF are unavailable, or if the
    OCR pass produces nothing usable. Never raises.

    OCR is expensive (Tesseract is ~1-3 seconds per page); we cap at
    the first 5 pages so a 200-page scan doesn't dominate the scan
    runtime. Most scanned-PDF events the user cares about have their
    headline content on the first 1-3 pages anyway.
    """
    try:
        import pytesseract  # type: ignore
        from PIL import Image  # type: ignore
    except ImportError:
        return ""
    try:
        import fitz  # type: ignore  # PyMuPDF
    except ImportError:
        return ""

    parts: List[str] = []
    try:
        doc = fitz.open(path)
        try:
            n_pages = min(len(doc), 5)
            for page_idx in range(n_pages):
                try:
                    page = doc[page_idx]
                    pix = page.get_pixmap(dpi=200)
                    img = Image.frombytes(
                        "RGB", (pix.width, pix.height), pix.samples,
                    )
                    text = pytesseract.image_to_string(img)
                    if text and text.strip():
                        parts.append(f"--- page {page_idx + 1} ---\n{text.strip()}")
                except Exception as exc:
                    logger.debug(
                        "OCR page %d failed for %s: %s",
                        page_idx, path, exc,
                    )
        finally:
            doc.close()
    except Exception as exc:
        logger.debug("OCR fallback failed for %s: %s", path, exc)
        return ""
    return "\n\n".join(parts)


def _docx_read_text(path: str) -> str:
    """Extract text from a DOCX using python-docx. Returns '' on any failure.

    v16.6.0 (Batch C7): record corrupt-file exceptions (BadZipFile,
    KeyError, PackageNotFoundError) so ``read_text_with_status`` can
    surface the real cause to the scan pipeline.
    """
    try:
        from docx import Document  # type: ignore
        doc = Document(path)
        return "\n".join(p.text for p in doc.paragraphs if p.text)
    except Exception as exc:
        _record_extraction_error(path, "python-docx", exc)
        logger.debug("DOCX text extraction failed for %s: %s", path, exc)
        return ""


def _xlsx_read_text(path: str) -> str:
    """Extract text from an XLSX using openpyxl.

    v16.4.0 (AUDIT-1b) — pre-v16.4 ``_extract_text_office`` returned
    ``""`` for xlsx, which combined with the empty image extractor
    in ``extract_embedded_images`` produced 0 bytes / 0 images for
    every spreadsheet. The audit's representative XLSX (`220928
    exhibition size.xlsx`) has 1.2 KB of legitimate content (a
    component-size table) plus 40 inline images — none of which
    landed in any note. openpyxl reads the cell grid; the per-cell
    text is concatenated tab-separated per row, with one
    ``# {sheet_name}`` heading per worksheet.
    """
    try:
        import openpyxl  # type: ignore
        wb = openpyxl.load_workbook(path, data_only=True, read_only=True)
        parts: List[str] = []
        for sheet in wb.worksheets:
            parts.append(f"# {sheet.title}")
            for row in sheet.iter_rows(values_only=True):
                # Drop trailing all-empty cells but preserve interior
                # blanks so column alignment stays meaningful.
                cells = [
                    "" if v is None else str(v)
                    for v in row
                ]
                while cells and cells[-1] == "":
                    cells.pop()
                if cells:
                    parts.append("\t".join(cells))
            parts.append("")  # blank line between sheets
        try:
            wb.close()
        except Exception:
            pass
        return "\n".join(parts).strip()
    except Exception as exc:
        # v16.6.0 (Batch C7): the SSS field report's truncated XLSX
        # raised BadZipFile here; pre-v16.6 the message vanished.
        _record_extraction_error(path, "openpyxl", exc)
        logger.debug("XLSX text extraction failed for %s: %s", path, exc)
        return ""


def _pptx_read_text(path: str) -> str:
    """Extract text from a PPTX using python-pptx. Returns '' on any failure.

    v16.6.0 (Batch C7): record corrupt-zip / parse exceptions in the
    extraction-error registry.
    """
    try:
        from pptx import Presentation  # type: ignore
        prs = Presentation(path)
        parts: List[str] = []
        for slide in prs.slides:
            for shape in slide.shapes:
                if hasattr(shape, "text") and shape.text:
                    parts.append(shape.text)
        return "\n".join(parts)
    except Exception as exc:
        _record_extraction_error(path, "python-pptx", exc)
        logger.debug("PPTX text extraction failed for %s: %s", path, exc)
        return ""


def _plain_read_text(path: str) -> str:
    """Read a plain-text file. Returns '' on any failure.

    v16.4.0 (AUDIT-4): for ``.rtf`` files, runs the bytes through
    ``striprtf`` to get unformatted text. striprtf is a tiny pure-Python
    package; if it's absent we fall back to soffice headless and finally
    to a literal byte read (which gives the user RTF source, not ideal
    but better than ``""``).
    """
    p = Path(path)
    ext = p.suffix.lstrip(".").lower()
    if ext == "rtf":
        return _rtf_read_text(path)
    try:
        return p.read_text(encoding="utf-8", errors="replace")
    except Exception as exc:
        logger.debug("Plain text read failed for %s: %s", path, exc)
        return ""


def _rtf_read_text(path: str) -> str:
    """Extract text from an RTF document.

    Pipeline: striprtf → soffice headless → literal-bytes fallback.
    Never raises.
    """
    # 1. striprtf is the lightweight pure-Python path.
    try:
        from striprtf.striprtf import rtf_to_text  # type: ignore
        raw = Path(path).read_text(encoding="utf-8", errors="replace")
        out = rtf_to_text(raw)
        if out and out.strip():
            return out
    except ImportError:
        pass
    except Exception as exc:
        logger.debug("striprtf failed for %s: %s", path, exc)

    # 2. LibreOffice headless fallback — works without striprtf.
    text = _soffice_convert_to_txt(path)
    if text:
        return text

    # 3. Last resort — return the raw bytes so the user sees RTF source
    # rather than a silent skip. The garbled-extract gate in scan_pipeline
    # will likely flag it; that's the right signal that a striprtf install
    # is needed.
    try:
        return Path(path).read_text(encoding="utf-8", errors="replace")
    except Exception:
        return ""


def _soffice_convert_to_txt(path: str) -> str:
    """Shell out to LibreOffice headless and return the converted text.

    Used as a shared fallback for RTF (and could be reused for other
    plain-but-tricky formats). Returns '' on any failure.
    """
    import shutil as _shutil
    import subprocess as _sp
    import tempfile as _tf
    binaries = ("soffice", "libreoffice")
    macos_apps = ("/Applications/LibreOffice.app/Contents/MacOS/soffice",)
    exe = ""
    for name in binaries:
        found = _shutil.which(name)
        if found:
            exe = found
            break
    if not exe:
        for app in macos_apps:
            if Path(app).exists():
                exe = app
                break
    if not exe:
        return ""
    with _tf.TemporaryDirectory() as td:
        try:
            proc = _sp.run(
                [exe, "--headless", "--convert-to", "txt", "--outdir", td, path],
                capture_output=True, timeout=60, check=False,
            )
        except Exception as exc:
            logger.debug("soffice convert failed for %s: %s", path, exc)
            return ""
        if proc.returncode != 0:
            return ""
        out_file = Path(td) / f"{Path(path).stem}.txt"
        if not out_file.exists():
            return ""
        try:
            return out_file.read_text(encoding="utf-8", errors="replace")
        except Exception:
            return ""


# ---------------------------------------------------------------------------
# Dispatch tables (v14.8 unification)
# ---------------------------------------------------------------------------
#
# Before v14.8, read_text() and extract_images() were long if/elif chains on
# `cfg.category`. Adding a new category required editing both chains AND
# the registry AND (for delegated types) the handler_dispatcher module.
#
# Now the dispatch is table-driven. Each category has two entries:
#
#   _TEXT_DISPATCH[category] = (needs_ext: bool, fn)
#     fn(path, workdir, ext) -> str — same signature regardless of needs
#     When not needs_ext, `ext` is ignored.
#
#   _IMAGE_DISPATCH[category] = fn
#     fn(path, workdir, ext) -> List[Path] — same uniform signature.
#
# Adding a new category is one entry in each table. Categories that should
# fall through to `handler_dispatcher` (CAD, vector-ai, raster-psd, etc.)
# do NOT need entries — they are handled by the default branch that checks
# `handler_dispatcher.is_delegated`.


def _extract_text_pdf(path, workdir, ext): return _pdf_read_text(path)
def _extract_text_plain(path, workdir, ext): return _plain_read_text(path)


def _extract_text_office(path, workdir, ext):
    if ext in ("docx", "doc"):
        return _docx_read_text(path)
    if ext in ("pptx", "ppt"):
        return _pptx_read_text(path)
    if ext == "xlsx":
        # v16.4.0 (AUDIT-1b) — wire openpyxl-based xlsx text extraction.
        return _xlsx_read_text(path)
    # xls handled via legacy spreadsheet path / soffice fallback.
    return ""


def _extract_images_passthrough(path, workdir, ext):
    return [Path(path)]


def _extract_images_container(path, workdir, ext):
    return _delegate_extract_images(Path(path), ext)


_TEXT_DISPATCH = {
    "document-pdf": _extract_text_pdf,
    "document-office": _extract_text_office,
    "text-plain": _extract_text_plain,
}


_IMAGE_DISPATCH = {
    "image-raster": _extract_images_passthrough,
    "image-vector": _extract_images_passthrough,
    "document-pdf": _extract_images_container,
    "document-office": _extract_images_container,
}


def _delegate_extract_images(src_path: Path, file_type: str) -> List[Path]:
    """Delegate to extract_embedded_images.extract for container types."""
    try:
        import extract_embedded_images  # type: ignore
        out_dir = src_path.parent / f"_extracted_{src_path.stem}"
        return extract_embedded_images.extract(src_path, out_dir, file_type)
    except Exception as exc:
        logger.debug("extract_embedded_images failed for %s: %s", src_path, exc)
        return []


def read_text(path: str, workdir: Optional[str] = None) -> str:
    """Extract text from `path` according to its file type.

    Looks up the category via `get_handler()`, then dispatches via
    `_TEXT_DISPATCH`. Unknown categories that are declared delegated
    (CAD, legacy Office, etc.) go to `handler_dispatcher`, which loads
    the per-extension module from `<workdir>/.vault-bridge/handlers/`.
    Everything else returns '' without raising.
    """
    cfg = get_handler(path)
    if cfg is None or not cfg.extract_text:
        return ""

    p = Path(path)
    if not p.exists():
        return ""

    ext = p.suffix.lstrip(".").lower()

    fn = _TEXT_DISPATCH.get(cfg.category)
    if fn is not None:
        return fn(path, workdir, ext)
    if handler_dispatcher.is_delegated(cfg.category):
        return handler_dispatcher.read_text(workdir, cfg.category, path)
    return ""


def read_text_with_status(
    path: str, workdir: Optional[str] = None,
) -> "tuple[str, Optional[str]]":
    """Extract text from `path`; return ``(text, error_msg)``.

    v16.5.0 (Fix A) — distinguishes "handler ran cleanly and produced
    nothing" from "handler raised". Pre-v16.5 the silent-swallow at
    handler-dispatch layer hid corrupt-file failures (BadZipFile,
    odafc binary missing, etc.). Returning the error string lets
    ``scan_pipeline`` surface the real cause to the user.

    Implementation: wraps ``read_text(path, workdir)`` with a try/except
    so test fixtures that mock ``read_text`` still fire. For the
    delegated path we also consult ``handler_dispatcher.read_text_with_status``
    to recover the underlying handler exception when ``read_text``
    swallowed it.
    """
    cfg = get_handler(path)
    if cfg is None or not cfg.extract_text:
        return "", None
    p = Path(path)
    if not p.exists():
        return "", None
    # Clear any prior extraction error before running so we don't
    # surface a stale message from an unrelated previous probe.
    consume_extraction_error(path)
    try:
        text = read_text(path, workdir=workdir)
    except Exception as exc:
        return "", f"{type(exc).__name__}: {exc}"
    # v16.6.0 (Batch C7): even when text is non-empty we expose any
    # recorded library exception (e.g. PDF that yielded text from
    # page 1 then PyPDF2 raised on page 2). Empty + recorded error is
    # the corrupt-file case.
    recorded = consume_extraction_error(path)
    if text:
        return text, recorded
    if recorded:
        return "", recorded
    # Empty result — for delegated categories, ask the dispatcher's
    # status-aware variant whether the handler raised. For built-in
    # categories an empty result is genuinely "nothing to extract".
    if handler_dispatcher.is_delegated(cfg.category):
        _, err = handler_dispatcher.read_text_with_status(
            workdir, cfg.category, path,
        )
        return "", err
    return "", None


def extract_images(path: str, workdir: Optional[str] = None) -> List[Path]:
    """Return the images for `path` according to its file type.

    Same dispatch shape as `read_text`: `_IMAGE_DISPATCH` handles the
    core categories; delegated categories (CAD, vector-ai, raster-psd,
    legacy-office, 3dm) go through `handler_dispatcher` so the
    per-extension workdir handler can render pages.
    """
    cfg = get_handler(path)
    if cfg is None or not cfg.extract_images:
        return []

    p = Path(path)
    if not p.exists():
        return []

    ext = p.suffix.lstrip(".").lower()

    fn = _IMAGE_DISPATCH.get(cfg.category)
    if fn is not None:
        return fn(path, workdir, ext)
    if handler_dispatcher.is_delegated(cfg.category):
        return handler_dispatcher.extract_images(workdir, cfg.category, path)
    return []


def extract_images_with_status(
    path: str, workdir: Optional[str] = None,
) -> "tuple[List[Path], Optional[str]]":
    """Same as :func:`extract_images`; also returns an error string when
    the handler raised. v16.5.0 (Fix A).

    Wraps ``extract_images(path, workdir)`` with a try/except so test
    fixtures that mock ``extract_images`` still fire correctly. For
    delegated categories we additionally consult the dispatcher's
    status-aware variant on empty results to recover errors that the
    inner handler swallowed.
    """
    cfg = get_handler(path)
    if cfg is None or not cfg.extract_images:
        return [], None
    p = Path(path)
    if not p.exists():
        return [], None
    try:
        paths = extract_images(path, workdir=workdir)
    except Exception as exc:
        return [], f"{type(exc).__name__}: {exc}"
    if paths:
        return list(paths), None
    if handler_dispatcher.is_delegated(cfg.category):
        _, err = handler_dispatcher.extract_images_with_status(
            workdir, cfg.category, path,
        )
        return [], err
    return [], None


def handle(path: str, workdir: Optional[str] = None) -> HandlerResult:
    """Process a file and return a HandlerResult.

    For known extensions:
      - Calls read_text() if extract_text is True, else sets text=''.
      - Calls extract_images() if extract_images is True, else sets images=[].
      - skipped=False, category=cfg.category.

    For unknown/empty/no-extension paths:
      - Returns HandlerResult(text=None, images=[], skipped=True, category='unknown').

    `workdir` is forwarded to read_text/extract_images so delegated
    categories (CAD, legacy Office) can dispatch to the per-extension
    handler modules under `<workdir>/.vault-bridge/handlers/`.

    Never raises.
    """
    cfg = get_handler(path)
    if cfg is None:
        return HandlerResult(text=None, images=[], skipped=True, category="unknown")

    try:
        text = read_text(path, workdir=workdir) if cfg.extract_text else ""
        images = extract_images(path, workdir=workdir) if cfg.extract_images else []
    except Exception as exc:
        logger.warning("handle() error processing %s: %s", path, exc)
        text = ""
        images = []

    return HandlerResult(
        text=text,
        images=images,
        skipped=False,
        category=cfg.category,
    )
