"""File-type handler registry for vault-bridge.

Generated by scripts/generate_file_type_handlers.py — but also usable standalone.

Provides:
  HANDLERS   — dict[str, HandlerConfig] mapping extension → handler config
  get_handler(path) -> HandlerConfig | None
  read_text(path, workdir=None) -> str
  extract_images(path, workdir=None) -> list[Path]
  handle(path, workdir=None) -> HandlerResult

Categories:
  document-pdf      — PDF files (PyPDF2 text + embedded image extraction)
  document-office   — DOCX / PPTX / XLSX (python-docx / python-pptx)
  image-raster      — JPG PNG GIF WEBP BMP TIFF HEIC (Pillow passthrough)
  image-vector      — SVG AI EPS (passthrough; no compression)
  video             — MP4 MOV AVI MKV etc. (skipped — no text/image extraction)
  audio             — MP3 WAV FLAC AAC etc. (skipped)
  text-plain        — TXT MD RST CSV (raw UTF-8 read)
  archive           — ZIP RAR 7Z TAR (skipped)

Delegated categories (v14.3, F1/F6) — dispatched to per-extension handler
modules under `<workdir>/.vault-bridge/handlers/`:
  cad-dxf, cad-dwg, cad-3dm, vector-ai, raster-psd,
  document-office-legacy, spreadsheet-legacy

These are opt-in via /vault-bridge:setup. When the workdir or the handler
file is missing, read_text/extract_images return empty for them rather
than raising — the capability gracefully degrades.

Python 3.9 compatible.
"""
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

import handler_dispatcher

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# HandlerConfig — immutable descriptor per extension category
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class HandlerConfig:
    """Descriptor for how vault-bridge should process a given file category.

    Attributes:
        category:       Slug identifying the file category (e.g. 'document-pdf').
        extract_text:   Whether to attempt text extraction from this file type.
        extract_images: Whether to attempt image extraction / passthrough.
        compress:       Whether to compress extracted images (JPEG, strip EXIF).
        run_vision:     Whether to run LLM vision on extracted images.
        render_pages:   Whether the handler renders pages to images (e.g. DXF, AI, PSD).
    """
    category: str
    extract_text: bool
    extract_images: bool
    compress: bool
    run_vision: bool
    render_pages: bool = False


# ---------------------------------------------------------------------------
# HANDLERS registry
# ---------------------------------------------------------------------------

# Each category's config — defined once and shared across all extensions in
# that category to avoid duplication.
_PDF = HandlerConfig(
    category="document-pdf",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
)
_OFFICE = HandlerConfig(
    category="document-office",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=False,
)
_RASTER = HandlerConfig(
    category="image-raster",
    extract_text=False,
    extract_images=True,
    compress=True,
    run_vision=True,
)
_VECTOR = HandlerConfig(
    category="image-vector",
    extract_text=False,
    extract_images=True,
    compress=False,
    run_vision=False,
)
_VIDEO = HandlerConfig(
    category="video",
    extract_text=False,
    extract_images=False,
    compress=False,
    run_vision=False,
)
_AUDIO = HandlerConfig(
    category="audio",
    extract_text=False,
    extract_images=False,
    compress=False,
    run_vision=False,
)
_TEXT = HandlerConfig(
    category="text-plain",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
)
_ARCHIVE = HandlerConfig(
    category="archive",
    extract_text=False,
    extract_images=False,
    compress=False,
    run_vision=False,
)

# ---------------------------------------------------------------------------
# Visual/CAD handler configs
# ---------------------------------------------------------------------------

_OFFICE_LEGACY = HandlerConfig(
    category="document-office-legacy",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

_SPREADSHEET_LEGACY = HandlerConfig(
    category="spreadsheet-legacy",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

_CAD_DXF = HandlerConfig(
    category="cad-dxf",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=True,
)

_CAD_DWG = HandlerConfig(
    category="cad-dwg",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=True,
)

_VECTOR_AI = HandlerConfig(
    category="vector-ai",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=True,
)

_RASTER_PSD = HandlerConfig(
    category="raster-psd",
    extract_text=True,
    extract_images=True,
    compress=True,
    run_vision=True,
    render_pages=True,
)

_CAD_3DM = HandlerConfig(
    category="cad-3dm",
    extract_text=True,
    extract_images=False,
    compress=False,
    run_vision=False,
    render_pages=False,
)

HANDLERS: Dict[str, HandlerConfig] = {
    # document-pdf
    "pdf": _PDF,
    # document-office (XML formats)
    "docx": _OFFICE,
    "pptx": _OFFICE,
    "xlsx": _OFFICE,
    # document-office-legacy (binary OLE2 formats)
    "doc": _OFFICE_LEGACY,
    "ppt": _OFFICE_LEGACY,
    # spreadsheet-legacy (binary XLS)
    "xls": _SPREADSHEET_LEGACY,
    # image-raster
    "jpg": _RASTER,
    "jpeg": _RASTER,
    "png": _RASTER,
    "gif": _RASTER,
    "webp": _RASTER,
    "bmp": _RASTER,
    "tiff": _RASTER,
    "tif": _RASTER,
    "heic": _RASTER,
    "heif": _RASTER,
    # image-vector (SVG/EPS passthrough only; ai now routed to vector-ai)
    "svg": _VECTOR,
    "eps": _VECTOR,
    # vector-ai (Adobe Illustrator via PyMuPDF — renders pages)
    "ai": _VECTOR_AI,
    # raster-psd (Photoshop PSD via psd-tools — composites layers)
    "psd": _RASTER_PSD,
    # cad-dxf (AutoCAD DXF via ezdxf — renders modelspace)
    "dxf": _CAD_DXF,
    # cad-dwg (AutoCAD DWG via ezdxf native reader — renders modelspace)
    "dwg": _CAD_DWG,
    # cad-3dm (Rhino 3DM via rhino3dm — metadata only, no rendering)
    "3dm": _CAD_3DM,
    # video
    "mp4": _VIDEO,
    "mov": _VIDEO,
    "avi": _VIDEO,
    "mkv": _VIDEO,
    "wmv": _VIDEO,
    "m4v": _VIDEO,
    "webm": _VIDEO,
    # audio
    "mp3": _AUDIO,
    "wav": _AUDIO,
    "flac": _AUDIO,
    "aac": _AUDIO,
    "ogg": _AUDIO,
    "m4a": _AUDIO,
    # text-plain
    "txt": _TEXT,
    "md": _TEXT,
    "rst": _TEXT,
    "csv": _TEXT,
    # archive
    "zip": _ARCHIVE,
    "rar": _ARCHIVE,
    "7z": _ARCHIVE,
    "tar": _ARCHIVE,
}


# ---------------------------------------------------------------------------
# HandlerResult — output of handle()
# ---------------------------------------------------------------------------

@dataclass
class HandlerResult:
    """Result of processing a single file through handle().

    Attributes:
        text:     Extracted text, or '' if the category doesn't extract text,
                  or None if the file was skipped (unknown extension).
        images:   Extracted / passthrough image paths.
        skipped:  True when the extension is unrecognised or path is empty.
        category: The category slug from HandlerConfig, or 'unknown' when skipped.
    """
    text: Optional[str] = None
    images: List[Path] = field(default_factory=list)
    skipped: bool = False
    category: str = ""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_handler(path: str) -> Optional[HandlerConfig]:
    """Return the HandlerConfig for the given file path, or None if unrecognised.

    Lookup is by the last extension only (.tar.gz → 'gz').
    Case-insensitive. Leading dot removed.
    Returns None for empty paths, paths with no extension, and dot-files
    with no real extension (e.g. '.hidden').

    Args:
        path: File path as string (may be relative or absolute).

    Returns:
        HandlerConfig or None.
    """
    if not path:
        return None

    p = Path(path)
    suffix = p.suffix  # '' or '.ext'
    if not suffix:
        return None

    ext = suffix.lstrip(".").lower()
    if not ext:
        # Dot-file like '.hidden' — suffix is '.hidden', ext is 'hidden'
        # But Path('.hidden').suffix == '' on Python 3.9, so this branch is
        # actually unreachable for dot-files.  Left for clarity.
        return None

    # Dot-file guard: Path('.hidden').stem == '.hidden', .suffix == ''
    # So we only reach here with a real extension.
    return HANDLERS.get(ext)


# ---------------------------------------------------------------------------
# Private per-format helpers
# ---------------------------------------------------------------------------

def _pdf_read_text(path: str) -> str:
    """Extract text from a PDF using PyPDF2. Returns '' on any failure."""
    try:
        import PyPDF2  # type: ignore
        reader = PyPDF2.PdfReader(path)
        parts: List[str] = []
        for page in reader.pages:
            try:
                t = page.extract_text()
                if t:
                    parts.append(t)
            except Exception:
                pass
        return "\n".join(parts)
    except Exception as exc:
        logger.debug("PDF text extraction failed for %s: %s", path, exc)
        return ""


def _docx_read_text(path: str) -> str:
    """Extract text from a DOCX using python-docx. Returns '' on any failure."""
    try:
        from docx import Document  # type: ignore
        doc = Document(path)
        return "\n".join(p.text for p in doc.paragraphs if p.text)
    except Exception as exc:
        logger.debug("DOCX text extraction failed for %s: %s", path, exc)
        return ""


def _pptx_read_text(path: str) -> str:
    """Extract text from a PPTX using python-pptx. Returns '' on any failure."""
    try:
        from pptx import Presentation  # type: ignore
        prs = Presentation(path)
        parts: List[str] = []
        for slide in prs.slides:
            for shape in slide.shapes:
                if hasattr(shape, "text") and shape.text:
                    parts.append(shape.text)
        return "\n".join(parts)
    except Exception as exc:
        logger.debug("PPTX text extraction failed for %s: %s", path, exc)
        return ""


def _plain_read_text(path: str) -> str:
    """Read a plain-text file. Returns '' on any failure."""
    try:
        return Path(path).read_text(encoding="utf-8", errors="replace")
    except Exception as exc:
        logger.debug("Plain text read failed for %s: %s", path, exc)
        return ""


# Categories that support text extraction, mapped to their reader helper.
_TEXT_READERS = {
    "document-pdf": _pdf_read_text,
    "document-office": None,  # dispatched per sub-format below
    "text-plain": _plain_read_text,
}


def read_text(path: str, workdir: Optional[str] = None) -> str:
    """Extract text from path according to its file type.

    When `workdir` is provided and the file's category is delegated
    (CAD, legacy Office, etc.), the per-extension handler module at
    `<workdir>/.vault-bridge/handlers/<category>_<ext>.py` is loaded
    and its `read_text` is called. Falls back to '' if the handler
    is missing or fails.

    Returns:
        Extracted text as a string, or '' when:
        - the file type doesn't support text extraction
        - the file doesn't exist
        - any extraction error occurs
        Never raises.
    """
    cfg = get_handler(path)
    if cfg is None or not cfg.extract_text:
        return ""

    p = Path(path)
    if not p.exists():
        return ""

    ext = p.suffix.lstrip(".").lower()

    if cfg.category == "document-pdf":
        return _pdf_read_text(path)
    elif cfg.category == "document-office":
        if ext in ("docx", "doc"):
            return _docx_read_text(path)
        elif ext in ("pptx", "ppt"):
            return _pptx_read_text(path)
        else:
            # xlsx/xls — no text extraction
            return ""
    elif cfg.category == "text-plain":
        return _plain_read_text(path)
    elif handler_dispatcher.is_delegated(cfg.category):
        return handler_dispatcher.read_text(workdir, cfg.category, path)
    else:
        return ""


# ---------------------------------------------------------------------------
# _delegate_extract_images — thin wrapper around extract_embedded_images
# so tests can mock it cleanly
# ---------------------------------------------------------------------------

def _delegate_extract_images(src_path: Path, file_type: str) -> List[Path]:
    """Delegate to extract_embedded_images.extract for container types."""
    try:
        import extract_embedded_images  # type: ignore
        out_dir = src_path.parent / f"_extracted_{src_path.stem}"
        return extract_embedded_images.extract(src_path, out_dir, file_type)
    except Exception as exc:
        logger.debug("extract_embedded_images failed for %s: %s", src_path, exc)
        return []


def extract_images(path: str, workdir: Optional[str] = None) -> List[Path]:
    """Extract or return images for the given file path.

    - image-raster / image-vector → returns [Path(path)] (passthrough).
    - document-pdf / document-office → delegates to extract_embedded_images.
    - CAD / legacy-office / vector-ai / raster-psd (v14.3, F1) → dispatches
      to per-extension handler at `<workdir>/.vault-bridge/handlers/`. When
      `workdir` is None the dispatch is a no-op — the caller (scan_pipeline)
      is responsible for threading workdir through; tests and direct library
      use that don't need these types work unchanged.
    - Everything else (video, audio, text-plain, archive, nonexistent) → [].

    Never raises.
    """
    cfg = get_handler(path)
    if cfg is None or not cfg.extract_images:
        return []

    p = Path(path)
    if not p.exists():
        return []

    ext = p.suffix.lstrip(".").lower()

    if cfg.category in ("image-raster", "image-vector"):
        return [p]
    elif cfg.category in ("document-pdf", "document-office"):
        return _delegate_extract_images(p, ext)
    elif handler_dispatcher.is_delegated(cfg.category):
        return handler_dispatcher.extract_images(workdir, cfg.category, path)
    else:
        return []


def handle(path: str, workdir: Optional[str] = None) -> HandlerResult:
    """Process a file and return a HandlerResult.

    For known extensions:
      - Calls read_text() if extract_text is True, else sets text=''.
      - Calls extract_images() if extract_images is True, else sets images=[].
      - skipped=False, category=cfg.category.

    For unknown/empty/no-extension paths:
      - Returns HandlerResult(text=None, images=[], skipped=True, category='unknown').

    `workdir` is forwarded to read_text/extract_images so delegated
    categories (CAD, legacy Office) can dispatch to the per-extension
    handler modules under `<workdir>/.vault-bridge/handlers/`.

    Never raises.
    """
    cfg = get_handler(path)
    if cfg is None:
        return HandlerResult(text=None, images=[], skipped=True, category="unknown")

    try:
        text = read_text(path, workdir=workdir) if cfg.extract_text else ""
        images = extract_images(path, workdir=workdir) if cfg.extract_images else []
    except Exception as exc:
        logger.warning("handle() error processing %s: %s", path, exc)
        text = ""
        images = []

    return HandlerResult(
        text=text,
        images=images,
        skipped=False,
        category=cfg.category,
    )
