"""Handler installer for vault-bridge file-type handling.

Installs Python packages and generates handler stub files for each
supported file extension.

Public API
----------
    InstallResult          — dataclass for installation outcome
    install_builtin(ext, spec, handlers_dir) -> InstallResult
    install_custom(ext, spec, handlers_dir)  -> InstallResult
    generate_handler_stub(ext, spec, handlers_dir, version, source, variant) -> Path
    get_installed_version(pip_name) -> str

Python 3.9 compatible.
"""
import importlib.util
import logging
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Pattern templates directory
# ---------------------------------------------------------------------------

_PATTERNS_DIR = Path(__file__).parent / "handlers" / "patterns"

# Categories that support page rendering (render_pages=True)
_RENDER_PAGES_CATEGORIES = {"cad-dxf", "cad-dwg", "vector-ai", "raster-psd"}


def _load_pattern(category: str) -> Optional[str]:
    """Look up a pattern template for the given category slug.

    Converts hyphens to underscores to find the template file.
    E.g. "cad-dxf" -> "cad_dxf.py.tmpl".

    Args:
        category: Category slug (e.g. "cad-dxf", "vector-ai").

    Returns:
        Template file contents as a string, or None if no template exists.
    """
    tmpl_name = category.replace("-", "_") + ".py.tmpl"
    tmpl_path = _PATTERNS_DIR / tmpl_name
    if not tmpl_path.exists():
        return None
    try:
        return tmpl_path.read_text(encoding="utf-8")
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Template text for generated stubs
# ---------------------------------------------------------------------------

_TEMPLATE = """\
# AUTO-GENERATED by vault-bridge handler_installer.py
# Package: {pip_name}
# Version: {version}
# pip_name: {pip_name_header}
# import_name: {import_name}
# source: {source}
# generated_at: {generated_at}
# stdlib: {is_stdlib}
\"\"\"Handler stub for {ext} files using {pip_name_or_stdlib}.

This file was auto-generated by vault-bridge.
Do not edit manually -- regenerate via /vault-bridge:setup file-types.
\"\"\"
import logging

logger = logging.getLogger(__name__)

CAPABILITIES = {{
    "read_text": {read_text_cap},
    "extract_images": {extract_images_cap},
}}


def read_text(path: str) -> str:
    \"\"\"Extract text from a {ext} file.

    Returns:
        Extracted text as a string, or '' on any failure.
        Never raises.
    \"\"\"
    try:
{read_text_body}
    except Exception as exc:
        logger.debug("read_text failed for %s: %s", path, exc)
        return ""


def extract_images(path: str, out_dir: str) -> list:
    \"\"\"Extract images from a {ext} file to out_dir.

    Returns:
        List of extracted image paths, or [] on any failure.
        Never raises.
    \"\"\"
    try:
{extract_images_body}
    except Exception as exc:
        logger.debug("extract_images failed for %s: %s", path, exc)
        return []
"""

# Per-variant body templates
_READ_TEXT_BODY_CAPABLE = """\
        import {import_name} as _pkg
        # TODO: implement using {import_name}
        return ""
"""

_READ_TEXT_BODY_STDLIB = """\
        from pathlib import Path as _Path
        return _Path(path).read_text(encoding="utf-8", errors="replace")
"""

_READ_TEXT_BODY_SKIP = """\
        return ""
"""

_EXTRACT_IMAGES_BODY_CAPABLE = """\
        import {import_name} as _pkg
        # TODO: implement image extraction using {import_name}
        return []
"""

_EXTRACT_IMAGES_BODY_SKIP = """\
        return []
"""


# ---------------------------------------------------------------------------
# InstallResult dataclass
# ---------------------------------------------------------------------------

@dataclass
class InstallResult:
    """Result of a package installation attempt.

    Attributes:
        ok:             True if install and smoke-test succeeded.
        ext:            File extension this handler covers.
        pip_name:       Package installed (may be "" for stdlib).
        version:        Installed version string (or "" on failure).
        handler_module: Dotted module path of the generated stub.
        source:         "builtin" or "web".
        error:          Error message when ok=False; "" when ok=True.
    """
    ok: bool
    ext: str
    pip_name: str
    version: str
    handler_module: str
    source: str
    error: str = ""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _determine_variant(spec) -> str:
    """Determine stub variant from spec capabilities."""
    if spec.extract_text and spec.extract_images:
        return "text_and_images"
    elif spec.extract_text:
        return "text_only"
    else:
        return "images_only"


def _stub_filename(ext: str, spec) -> str:
    """Generate stub filename: {category}_{ext}.py"""
    ext_clean = ext.lstrip(".").lower()
    category_slug = spec.category.replace("-", "_")
    return f"{category_slug}_{ext_clean}.py"


def _handler_module_name(ext: str, spec) -> str:
    """Return dotted module path for the stub (e.g. handlers.document_pdf_pdfplumber)."""
    ext_clean = ext.lstrip(".").lower()
    pip_slug = spec.pip_name.replace("-", "_").replace(".", "_").lower()
    category_slug = spec.category.replace("-", "_")
    if pip_slug:
        return f"handlers.{category_slug}_{ext_clean}_{pip_slug}"
    return f"handlers.{category_slug}_{ext_clean}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_installed_version(pip_name: str) -> str:
    """Return the installed version of a package, or "" if not found.

    Uses importlib.metadata. Never raises.

    Args:
        pip_name: The pip package name (e.g. "pdfplumber").

    Returns:
        Version string, or "" on any failure.
    """
    if not pip_name:
        return ""
    try:
        import importlib.metadata
        return importlib.metadata.version(pip_name)
    except Exception:
        pass
    # Fallback: try pkg_resources
    try:
        import pkg_resources
        return pkg_resources.get_distribution(pip_name).version
    except Exception:
        return ""


def generate_handler_stub(
    ext: str,
    spec,
    handlers_dir: Path,
    version: str = "",
    source: str = "builtin",
    variant: str = "",
) -> Path:
    """Render and write a handler stub .py file to handlers_dir.

    Args:
        ext:          File extension (with or without leading dot).
        spec:         PackageSpec describing the package.
        handlers_dir: Directory where the stub will be written.
        version:      Package version string (informational).
        source:       "builtin" or "web".
        variant:      "text_only", "text_and_images", "images_only", or ""
                      (auto-detected from spec capabilities when empty).

    Returns:
        Path of the written stub file.
    """
    handlers_dir = Path(handlers_dir)
    handlers_dir.mkdir(parents=True, exist_ok=True)

    ext_clean = ext.lstrip(".").lower()
    is_stdlib = spec.pip_name == "" and spec.import_name == ""

    # Determine variant
    if not variant:
        variant = _determine_variant(spec)

    # Determine capabilities for this variant
    if variant == "text_only":
        read_text_cap = "True"
        extract_images_cap = "False"
    elif variant == "text_and_images":
        read_text_cap = "True"
        extract_images_cap = "True"
    elif variant == "images_only":
        read_text_cap = "False"
        extract_images_cap = "True"
    else:
        read_text_cap = str(spec.extract_text)
        extract_images_cap = str(spec.extract_images)

    # Build body blocks
    if read_text_cap == "True":
        if is_stdlib:
            read_text_body = _READ_TEXT_BODY_STDLIB
        elif spec.import_name:
            read_text_body = _READ_TEXT_BODY_CAPABLE.format(
                import_name=spec.import_name)
        else:
            read_text_body = _READ_TEXT_BODY_SKIP
    else:
        read_text_body = _READ_TEXT_BODY_SKIP

    if extract_images_cap == "True" and spec.import_name and not is_stdlib:
        extract_images_body = _EXTRACT_IMAGES_BODY_CAPABLE.format(
            import_name=spec.import_name)
    else:
        extract_images_body = _EXTRACT_IMAGES_BODY_SKIP

    pip_name_or_stdlib = spec.pip_name if spec.pip_name else "stdlib"
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Try to use a pattern template for this category
    render_pages_cap = spec.category in _RENDER_PAGES_CATEGORIES
    pattern_tmpl = _load_pattern(spec.category)
    if pattern_tmpl is not None:
        try:
            content = pattern_tmpl.format(
                package_name=spec.pip_name or "stdlib",
                pip_name=spec.pip_name,
                version=version or "",
                source=source,
                generated_at=generated_at,
                ext=ext_clean,
            )
        except Exception as exc:
            logger.debug("Pattern template render failed for %s: %s", spec.category, exc)
            pattern_tmpl = None  # fall through to generic template

    if pattern_tmpl is None:
        content = _TEMPLATE.format(
            pip_name=spec.pip_name,
            pip_name_header=f'"{spec.pip_name}"' if spec.pip_name else '""',
            import_name=spec.import_name,
            source=source,
            generated_at=generated_at,
            is_stdlib=str(is_stdlib),
            ext=ext_clean,
            pip_name_or_stdlib=pip_name_or_stdlib,
            read_text_cap=read_text_cap,
            extract_images_cap=extract_images_cap,
            read_text_body=read_text_body,
            extract_images_body=extract_images_body,
            version=version or "",
        )

    filename = _stub_filename(ext_clean, spec)
    out_path = handlers_dir / filename
    out_path.write_text(content, encoding="utf-8")
    return out_path


def _do_install(
    ext: str,
    spec,
    handlers_dir: Path,
    source: str,
) -> "InstallResult":
    """Shared implementation for install_builtin and install_custom."""
    handlers_dir = Path(handlers_dir)
    ext_clean = ext.lstrip(".").lower()
    is_stdlib = spec.pip_name == "" and spec.import_name == ""
    stub_path: Optional[Path] = None

    # --- stdlib: skip pip install ---
    if is_stdlib:
        version = ""
        stub_path = generate_handler_stub(ext_clean, spec, handlers_dir,
                                          version=version, source=source)
        return InstallResult(
            ok=True,
            ext=ext_clean,
            pip_name=spec.pip_name,
            version=version,
            handler_module=_handler_module_name(ext_clean, spec),
            source=source,
            error="",
        )

    # --- pip install ---
    cmd = [sys.executable, "-m", "pip", "install", spec.pip_name]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
    except Exception as exc:
        return InstallResult(
            ok=False,
            ext=ext_clean,
            pip_name=spec.pip_name,
            version="",
            handler_module="",
            source=source,
            error=str(exc),
        )

    if result.returncode != 0:
        error_msg = result.stderr.strip() or f"pip install {spec.pip_name} failed"
        return InstallResult(
            ok=False,
            ext=ext_clean,
            pip_name=spec.pip_name,
            version="",
            handler_module="",
            source=source,
            error=error_msg,
        )

    # --- verify import ---
    found = importlib.util.find_spec(spec.import_name)
    if found is None:
        return InstallResult(
            ok=False,
            ext=ext_clean,
            pip_name=spec.pip_name,
            version="",
            handler_module="",
            source=source,
            error=f"pip reported success but '{spec.import_name}' is not importable",
        )

    # --- write stub ---
    version = get_installed_version(spec.pip_name)
    stub_path = generate_handler_stub(ext_clean, spec, handlers_dir,
                                      version=version, source=source)

    # --- smoke-test: verify stub is valid Python and can be compiled ---
    try:
        content = stub_path.read_text(encoding="utf-8")
        compile(content, str(stub_path), "exec")
    except Exception as exc:
        # Rollback: delete the stub
        try:
            stub_path.unlink(missing_ok=True)
        except Exception:
            pass
        return InstallResult(
            ok=False,
            ext=ext_clean,
            pip_name=spec.pip_name,
            version=version,
            handler_module="",
            source=source,
            error=f"Stub smoke-test failed: {exc}",
        )

    return InstallResult(
        ok=True,
        ext=ext_clean,
        pip_name=spec.pip_name,
        version=version,
        handler_module=_handler_module_name(ext_clean, spec),
        source=source,
        error="",
    )


def install_builtin(
    ext: str,
    spec,
    handlers_dir: Path,
) -> "InstallResult":
    """Install a built-in package and generate its handler stub.

    Runs `pip install spec.pip_name`, verifies the import, writes a stub,
    and smoke-tests it. Rolls back (deletes stub) on any failure.

    Args:
        ext:          File extension (e.g. "pdf").
        spec:         PackageSpec from BUILTIN_REGISTRY.
        handlers_dir: Directory where handler stubs live.

    Returns:
        InstallResult with source="builtin".
    """
    return _do_install(ext, spec, handlers_dir, source="builtin")


def install_custom(
    ext: str,
    spec,
    handlers_dir: Path,
) -> "InstallResult":
    """Install a custom (web-searched) package and generate its handler stub.

    Same contract as install_builtin, but sets source="web".

    Args:
        ext:          File extension (e.g. "xps").
        spec:         PackageSpec constructed from search results.
        handlers_dir: Directory where handler stubs live.

    Returns:
        InstallResult with source="web".
    """
    return _do_install(ext, spec, handlers_dir, source="web")
