#!/usr/bin/env python3
"""vault-bridge deterministic CLAUDE.md renderer.

Generates a project-scoped CLAUDE.md at <workdir>/.vault-bridge/CLAUDE.md
from an EffectiveConfig. Handles edit detection via a SHA-256 hash stored
in a comment line; if the user has edited the file, the new render is
written to a CLAUDE.md.generated sidecar instead.

Usage (library):
    from render_claude_md import render, write, RenderResult

Usage (CLI):
    python3 render_claude_md.py --workdir .
    python3 render_claude_md.py --workdir . --dry-run
"""
import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

import local_config  # noqa: E402
import effective_config as ec  # noqa: E402
from effective_config import BUILTIN_FABRICATION_STOPWORDS, EffectiveConfig  # noqa: E402


# ---------------------------------------------------------------------------
# Output paths
# ---------------------------------------------------------------------------

def _claude_md_path(workdir) -> Path:
    return local_config.local_dir(workdir) / "CLAUDE.md"


def _sidecar_path(workdir) -> Path:
    return local_config.local_dir(workdir) / "CLAUDE.md.generated"


# ---------------------------------------------------------------------------
# RenderResult
# ---------------------------------------------------------------------------

@dataclass
class RenderResult:
    path: Path              # the main CLAUDE.md path
    written: bool           # True if the file was written this call
    was_edited: bool        # True if existing file's hash didn't match
    sidecar_path: Optional[Path]


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

_HASH_PLACEHOLDER = "<!-- vb-render-hash: {hash} -->"
_HASH_PATTERN = re.compile(r"<!-- vb-render-hash: ([0-9a-f]+) -->")

_RENDER_COMMENT = (
    "<!-- Auto-generated by scripts/render_claude_md.py. "
    "Edits preserved via CLAUDE.md.generated sidecar. -->"
)


def render(
    effective: EffectiveConfig,
    observed_subfolders: Optional[List[str]] = None,
) -> str:
    """Render a CLAUDE.md body for the given EffectiveConfig.

    Returns byte-identical output for equal inputs.
    The hash comment is injected after rendering.
    """
    body = _render_body(effective, observed_subfolders)
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()[:16]
    hash_line = _HASH_PLACEHOLDER.format(hash=digest)
    # Insert hash line as second line (after the title)
    lines = body.splitlines()
    # Find the first blank line after the title
    insert_at = 1
    for i, line in enumerate(lines):
        if i > 0 and line.strip() == "":
            insert_at = i
            break
    lines.insert(insert_at, hash_line)
    lines.insert(insert_at + 1, _RENDER_COMMENT)
    return "\n".join(lines) + "\n"


def _render_body(
    effective: EffectiveConfig,
    observed_subfolders: Optional[List[str]] = None,
) -> str:
    """Render body text WITHOUT the hash comment. Used for hash computation."""
    lines: List[str] = []

    lines.append("# vault-bridge — project operating rules")
    lines.append("")

    # --- Active configuration ---
    lines.append("## Active configuration")
    lines.append("")
    lines.append(f"- **Vault:** {effective.vault_name}")
    lines.append(f"- **Domain:** {effective.domain_name}")
    lines.append(f"- **Archive root:** `{effective.archive_root}`")
    lines.append(f"- **File system:** {effective.file_system_type}")
    lines.append(f"- **Fallback subfolder:** `{effective.fallback}`")
    lines.append("")

    # --- Observed structure ---
    lines.append("## Observed structure")
    lines.append("")
    if observed_subfolders:
        for sf in sorted(observed_subfolders):
            lines.append(f"- `{sf}`")
    else:
        lines.append("(not yet discovered — run a retro-scan)")
    lines.append("")

    # --- Effective routing rules ---
    lines.append("## Effective routing rules")
    lines.append("")
    lines.append("| Match | → Subfolder |")
    lines.append("|---|---|")
    for pattern in effective.routing_patterns:
        match = pattern.get("match", "")
        subfolder = pattern.get("subfolder", "")
        lines.append(f"| `{match}` | `{subfolder}` |")
    lines.append("")

    # --- Content overrides (optional section) ---
    if effective.content_overrides:
        lines.append("## Content overrides")
        lines.append("")
        lines.append("| Match | → Subfolder |")
        lines.append("|---|---|")
        for override in effective.content_overrides:
            when = override.get("when", "")
            subfolder = override.get("subfolder", "")
            lines.append(f"| `{when}` | `{subfolder}` |")
        lines.append("")

    # --- Skip patterns ---
    lines.append("## Skip patterns")
    lines.append("")
    for pat in sorted(effective.skip_patterns):
        lines.append(f"- `{pat}`")
    lines.append("")

    # --- Tags ---
    lines.append("## Tags applied to every note")
    lines.append("")
    for tag in sorted(effective.default_tags):
        lines.append(f"- `{tag}`")
    lines.append("")

    # --- Fabrication firewall stop-words ---
    lines.append("## Fabrication firewall stop-words")
    lines.append("")
    # Builtins in canonical order first, then extras alphabetised
    builtin_set = set(BUILTIN_FABRICATION_STOPWORDS)
    builtins_present = [sw for sw in BUILTIN_FABRICATION_STOPWORDS if sw in effective.fabrication_stopwords]
    extras = sorted([sw for sw in effective.fabrication_stopwords if sw not in builtin_set])
    for sw in builtins_present:
        lines.append(f'- "{sw}"')
    for sw in extras:
        lines.append(f'- "{sw}"')
    lines.append("")

    # --- Style ---
    lines.append("## Style")
    lines.append("")
    style = effective.style
    lines.append(f"- Writing voice: {style.get('writing_voice', '(not set)')}")
    word_count = style.get("summary_word_count", "(not set)")
    if isinstance(word_count, list):
        word_count = f"{word_count[0]}–{word_count[1]}"
    lines.append(f"- Summary word count: {word_count}")
    lines.append(f"- Filename pattern: `{style.get('note_filename_pattern', '(not set)')}`")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Hash extraction
# ---------------------------------------------------------------------------

def _extract_stored_hash(content: str) -> Optional[str]:
    """Extract the vb-render-hash value from the file content."""
    m = _HASH_PATTERN.search(content)
    if m:
        return m.group(1)
    return None


def _recompute_hash(content: str) -> str:
    """Recompute the SHA-256 hash of the content excluding the hash comment line."""
    lines = content.splitlines()
    body_lines = [l for l in lines if not _HASH_PATTERN.search(l) and _RENDER_COMMENT not in l]
    body_text = "\n".join(body_lines)
    # _render_body output ends with "\n" (trailing empty line + join produces trailing \n)
    # After splitlines/join we lose the trailing \n, so add it back:
    if not body_text.endswith("\n"):
        body_text = body_text + "\n"
    return hashlib.sha256(body_text.encode("utf-8")).hexdigest()[:16]


def _file_unchanged(existing_content: str, new_content: str) -> bool:
    """True if existing content is byte-for-byte identical to new content."""
    return existing_content == new_content


def _user_edited(existing_content: str) -> bool:
    """Return True if the on-disk content has been user-edited.

    Detected by: extracting stored hash, recomputing hash of body, comparing.
    If no hash line present → treat as edited.
    """
    stored = _extract_stored_hash(existing_content)
    if stored is None:
        return True  # No hash line → treat as edited
    recomputed = _recompute_hash(existing_content)
    return stored != recomputed


# ---------------------------------------------------------------------------
# Public write API
# ---------------------------------------------------------------------------

def write(
    workdir,
    effective: EffectiveConfig,
    observed_subfolders: Optional[List[str]] = None,
) -> RenderResult:
    """Render and write CLAUDE.md to <workdir>/.vault-bridge/CLAUDE.md.

    Edit detection:
      - If file missing → write normally.
      - If file content unchanged → skip write (written=False).
      - If hash matches body → overwrite.
      - If hash doesn't match body → user edited → write sidecar.
    """
    # Ensure directory exists
    local_config.local_dir(workdir).mkdir(exist_ok=True, parents=True)

    main_path = _claude_md_path(workdir)
    new_content = render(effective, observed_subfolders)

    if not main_path.exists():
        main_path.write_text(new_content, encoding="utf-8")
        return RenderResult(
            path=main_path,
            written=True,
            was_edited=False,
            sidecar_path=None,
        )

    existing_content = main_path.read_text(encoding="utf-8")

    # Byte-identical → no-op
    if _file_unchanged(existing_content, new_content):
        return RenderResult(
            path=main_path,
            written=False,
            was_edited=False,
            sidecar_path=None,
        )

    # Check if user edited
    if _user_edited(existing_content):
        # Write sidecar instead of overwriting
        sidecar = _sidecar_path(workdir)
        sidecar.write_text(new_content, encoding="utf-8")
        return RenderResult(
            path=main_path,
            written=True,
            was_edited=True,
            sidecar_path=sidecar,
        )

    # Hash matches but content differs (e.g., observed_subfolders changed) → overwrite
    main_path.write_text(new_content, encoding="utf-8")
    return RenderResult(
        path=main_path,
        written=True,
        was_edited=False,
        sidecar_path=None,
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render vault-bridge CLAUDE.md for a working directory."
    )
    parser.add_argument("--workdir", default=".", help="Working directory (default: cwd)")
    parser.add_argument("--dry-run", action="store_true", help="Print rendered content, don't write")
    args = parser.parse_args()

    workdir = Path(args.workdir).resolve()
    settings_path = local_config.settings_path(workdir)

    if not settings_path.exists():
        sys.stderr.write(
            f"render_claude_md: no .vault-bridge/settings.json found in {workdir}. "
            "Run /vault-bridge:setup first.\n"
        )
        return 2

    try:
        effective = ec.load_effective_config(workdir)
    except ec.SetupNeeded as e:
        sys.stderr.write(f"render_claude_md: {e}\n")
        return 2

    # Load observed_subfolders from settings if present
    observed_subfolders: Optional[List[str]] = None
    try:
        settings_data = json.loads(settings_path.read_text())
        ds = settings_data.get("discovered_structure", {})
        if ds:
            observed_subfolders = ds.get("observed_subfolders")
    except (json.JSONDecodeError, OSError):
        pass

    if args.dry_run:
        print(render(effective, observed_subfolders))
        return 0

    result = write(workdir, effective, observed_subfolders)

    if not result.written:
        print(f"CLAUDE.md unchanged: {result.path}")
    elif result.was_edited:
        print(f"User edits detected — sidecar written: {result.sidecar_path}")
        print(f"Original preserved: {result.path}")
    else:
        print(f"Written: {result.path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
