"""Scaffold the per-workdir transport.py helper from shipped templates.

Called by /vault-bridge:setup after domain configuration is complete.
Picks the right template(s) based on file_system_type, substitutes
placeholders, and writes <workdir>/.vault-bridge/transport.py.

For projects with a single FS type, a single-branch template is used.
For multi-domain projects with different FS types, a dispatch wrapper
with if/elif branches (one per distinct prefix) is generated.

Python 3.9 compatible.
"""
from pathlib import Path
from typing import Dict, List

# Path to the shipped template files
_TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "templates" / "transport"

# Template filenames by file_system_type
_TEMPLATE_FILES = {
    "local-path": "local.py.tmpl",
    "external-mount": "external-mount.py.tmpl",
    "nas-mcp": "nas-mcp.py.tmpl",
}


def _read_template(fs_type: str) -> str:
    """Read and return the raw template content for a file_system_type."""
    filename = _TEMPLATE_FILES.get(fs_type, "nas-mcp.py.tmpl")
    tmpl_path = _TEMPLATES_DIR / filename
    if tmpl_path.exists():
        return tmpl_path.read_text()
    # Fallback inline templates if the file is missing
    return _inline_template(fs_type)


def _inline_template(fs_type: str) -> str:
    """Return an inline fallback template when the .tmpl file is missing."""
    if fs_type == "local-path":
        return (
            '"""vault-bridge transport helper — local-path.\n'
            'Archive root: ${ARCHIVE_ROOT}\n"""\n'
            "from pathlib import Path\n\n\n"
            "def fetch_to_local(archive_path: str) -> Path:\n"
            "    p = Path(archive_path)\n"
            "    if not p.exists():\n"
            "        raise FileNotFoundError(f'Archive path does not exist: {archive_path}')\n"
            "    return p\n"
        )
    elif fs_type == "external-mount":
        return (
            '"""vault-bridge transport helper — external-mount.\n'
            'Archive root: ${ARCHIVE_ROOT}\n'
            'Mount point: ${MOUNT_POINT}\n"""\n'
            "import os\n"
            "from pathlib import Path\n\n\n"
            "def fetch_to_local(archive_path: str) -> Path:\n"
            "    mount_point = '${MOUNT_POINT}'\n"
            "    if not os.path.ismount(mount_point):\n"
            "        raise FileNotFoundError(\n"
            "            f'Mount point \"{mount_point}\" is not currently mounted.'\n"
            "        )\n"
            "    p = Path(archive_path)\n"
            "    if not p.exists():\n"
            "        raise FileNotFoundError(f'Archive path does not exist: {archive_path}')\n"
            "    return p\n"
        )
    else:
        # nas-mcp
        return (
            '"""vault-bridge transport helper — nas-mcp.\n'
            'YOU MUST EDIT THIS FILE.\n'
            'Archive root: ${ARCHIVE_ROOT}\n"""\n'
            "from pathlib import Path\n\n\n"
            "def fetch_to_local(archive_path: str) -> Path:\n"
            "    # TODO: implement your NAS fetch logic here.\n"
            "    raise NotImplementedError(\n"
            "        'Edit <workdir>/.vault-bridge/transport.py to implement fetch_to_local().'\n"
            "    )\n"
        )


def _render_single(domain: Dict) -> str:
    """Render a single-domain transport.py from a template."""
    fs_type = domain.get("file_system_type", "nas-mcp")
    archive_root = domain.get("archive_root", "")
    mount_point = domain.get("mount_point", archive_root)

    content = _read_template(fs_type)
    content = content.replace("${ARCHIVE_ROOT}", archive_root)
    content = content.replace("${MOUNT_POINT}", mount_point)
    return content


def _render_multi(domains: List[Dict]) -> str:
    """Render a multi-domain transport.py with prefix-dispatch branching."""
    lines: List[str] = []
    lines.append('"""vault-bridge transport helper — multi-domain.')
    lines.append("Generated by /vault-bridge:setup. Safe to edit.")
    lines.append('"""\n')
    lines.append("import os")
    lines.append("from pathlib import Path")
    lines.append("")
    lines.append("")

    # Collect per-domain fetch functions
    func_names: List[str] = []
    for i, domain in enumerate(domains):
        fs_type = domain.get("file_system_type", "nas-mcp")
        archive_root = domain.get("archive_root", "")
        mount_point = domain.get("mount_point", archive_root)
        domain_name = domain.get("name", f"domain_{i}")
        func_name = f"_fetch_{domain_name.replace('-', '_').replace(' ', '_')}"
        func_names.append((archive_root, func_name))

        if fs_type == "local-path":
            lines.append(f"def {func_name}(archive_path: str) -> Path:")
            lines.append(f"    # local-path domain: {domain_name} ({archive_root})")
            lines.append("    p = Path(archive_path)")
            lines.append("    if not p.exists():")
            lines.append("        raise FileNotFoundError(f'Archive path does not exist: {archive_path}')")
            lines.append("    return p")
        elif fs_type == "external-mount":
            lines.append(f"def {func_name}(archive_path: str) -> Path:")
            lines.append(f"    # external-mount domain: {domain_name} (mount: {mount_point})")
            lines.append(f"    if not os.path.ismount({mount_point!r}):")
            lines.append(f"        raise FileNotFoundError(")
            lines.append(f"            'Mount point {mount_point!r} is not currently mounted.'")
            lines.append("        )")
            lines.append("    p = Path(archive_path)")
            lines.append("    if not p.exists():")
            lines.append("        raise FileNotFoundError(f'Archive path does not exist: {archive_path}')")
            lines.append("    return p")
        else:
            # nas-mcp
            lines.append(f"def {func_name}(archive_path: str) -> Path:")
            lines.append(f"    # nas-mcp domain: {domain_name} ({archive_root})")
            lines.append("    # TODO: implement your NAS fetch logic here.")
            lines.append("    raise NotImplementedError(")
            escaped = domain_name.replace("'", "\\'")
            lines.append(f"        'Edit transport.py to implement fetch_to_local() for domain {escaped}.'")
            lines.append("    )")
        lines.append("")
        lines.append("")

    # Dispatch function
    lines.append("def fetch_to_local(archive_path: str) -> Path:")
    lines.append('    """Dispatch to per-domain fetch based on archive_path prefix."""')
    for archive_root, func_name in func_names:
        lines.append(f"    if archive_path.startswith({archive_root!r}):")
        lines.append(f"        return {func_name}(archive_path)")
    lines.append("    raise FileNotFoundError(")
    lines.append("        f'archive_path {archive_path!r} does not match any configured domain.'")
    lines.append("    )")
    lines.append("")

    return "\n".join(lines)


def scaffold_transport(workdir: Path, domains: List[Dict]) -> Path:
    """Write <workdir>/.vault-bridge/transport.py.

    Args:
        workdir: The project working directory.
        domains: List of domain dicts, each with at minimum:
            - "archive_root": str
            - "file_system_type": str  ("local-path", "nas-mcp", "external-mount")
            - "name": str (domain slug)
            - "mount_point": str (optional, for external-mount)

    Returns:
        Path to the written transport.py file.
    """
    workdir = Path(workdir)
    vault_bridge_dir = workdir / ".vault-bridge"
    vault_bridge_dir.mkdir(parents=True, exist_ok=True)
    out_path = vault_bridge_dir / "transport.py"

    if not domains:
        # Write a minimal stub
        content = _render_single({"file_system_type": "nas-mcp", "archive_root": ""})
    elif len(domains) == 1:
        content = _render_single(domains[0])
    else:
        # Check if all domains have the same FS type
        fs_types = {d.get("file_system_type", "nas-mcp") for d in domains}
        if len(fs_types) == 1:
            # Same type for all — use a single template with the first domain's root
            content = _render_single(domains[0])
        else:
            content = _render_multi(domains)

    out_path.write_text(content)
    return out_path
