"""Tests for scripts/handler_refresh.py — drift detection + refresh.

v16.7.0 (TLS Bug 4). Pre-v16.7 self-update only refreshed slash-command
templates; per-extension handler files in
``<workdir>/.vault-bridge/handlers/`` were rendered once at setup and
never refreshed. ``detect_outdated_handlers`` walks the installed
handlers against the current pattern templates so self-update can
prompt to refresh.

Python 3.9 compatible.
"""
import sys
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parents[2] / "scripts"
sys.path.insert(0, str(SCRIPTS))

import handler_refresh  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_workdir_with_handler(tmp_path: Path, handler_filename: str, body: str) -> Path:
    """Materialise a fake workdir with a single installed handler."""
    handlers_dir = tmp_path / ".vault-bridge" / "handlers"
    handlers_dir.mkdir(parents=True)
    (handlers_dir / handler_filename).write_text(body, encoding="utf-8")
    return tmp_path


# ---------------------------------------------------------------------------
# detect_outdated_handlers — empty / clean / drift cases
# ---------------------------------------------------------------------------

class TestDetectOutdatedHandlers:
    def test_no_workdir_returns_empty(self, tmp_path):
        assert handler_refresh.detect_outdated_handlers(str(tmp_path)) == []

    def test_handler_matching_template_not_flagged(self, tmp_path):
        """An installed handler whose body matches the current pattern
        template (modulo volatile install metadata) is NOT flagged."""
        # Use the actual document_office.py.tmpl rendered with ext=docx
        plugin_root = Path(__file__).resolve().parents[2]
        tmpl_text = (
            plugin_root
            / "scripts" / "handlers" / "patterns" / "document_office.py.tmpl"
        ).read_text()
        rendered = handler_refresh._render_template_skeleton(tmpl_text, ext="docx")
        wd = _make_workdir_with_handler(
            tmp_path, "document_office_docx.py", rendered,
        )
        drift = handler_refresh.detect_outdated_handlers(str(wd))
        assert drift == []

    def test_stale_dwg_handler_flagged_with_actionable_reason(self, tmp_path):
        """The TLS Bug 4 reproducer: a 2026-04-23 cad_dwg_dwg.py without
        the LibreDWG two-converter path. detect_outdated_handlers must
        surface the missing function names so the user knows what
        changed."""
        stale = (
            "# AUTO-GENERATED by vault-bridge handler_installer.py\n"
            "# generated_at: 2026-04-23T14:15:24Z\n"
            "# note: ezdxf + odafc only\n"
            '"""Handler stub for dwg files — DWG via ODA only."""\n'
            "def read_text(path):\n"
            "    from ezdxf.addons import odafc\n"
            "    try:\n"
            "        doc = odafc.readfile(path)\n"
            "    except Exception:\n"
            "        return ''\n"
            "    return ''\n"
            "def extract_images(path, out_dir):\n"
            "    return []\n"
        )
        wd = _make_workdir_with_handler(tmp_path, "cad_dwg_dwg.py", stale)
        drift = handler_refresh.detect_outdated_handlers(str(wd))
        assert len(drift) == 1
        d = drift[0]
        assert d.category == "cad-dwg"
        assert d.ext == "dwg"
        # The summary names the salient missing functions so the
        # operator can tell what changed.
        assert "_convert_via_libredwg" in d.reason

    def test_volatile_lines_ignored(self, tmp_path):
        """Different `# generated_at:` / `# Version:` should not flag."""
        plugin_root = Path(__file__).resolve().parents[2]
        tmpl_text = (
            plugin_root
            / "scripts" / "handlers" / "patterns" / "image_raster.py.tmpl"
        ).read_text()
        rendered = handler_refresh._render_template_skeleton(tmpl_text, ext="png")
        # Inject explicit volatile lines that match what the installer writes
        installed = (
            "# generated_at: 2025-11-20T12:34:56Z\n"
            "# Version: 11.4.1\n"
            "# package_name: pillow\n"
            + rendered
        )
        wd = _make_workdir_with_handler(
            tmp_path, "image_raster_png.py", installed,
        )
        drift = handler_refresh.detect_outdated_handlers(str(wd))
        assert drift == []

    def test_handler_without_pattern_template_not_flagged(self, tmp_path):
        """Custom handlers (no matching pattern template) are left
        alone — we don't have an authoritative source to refresh against."""
        custom = (
            '"""Custom user handler for some weird format."""\n'
            "def read_text(path):\n"
            "    return ''\n"
            "def extract_images(path, out_dir):\n"
            "    return []\n"
        )
        wd = _make_workdir_with_handler(tmp_path, "custom_xyz.py", custom)
        drift = handler_refresh.detect_outdated_handlers(str(wd))
        assert drift == []


# ---------------------------------------------------------------------------
# refresh_handlers — re-renders selected entries
# ---------------------------------------------------------------------------

class TestRefreshHandlers:
    def test_refresh_replaces_stale_dwg_with_current_template(self, tmp_path):
        """End-to-end: a stale DWG handler gets refreshed and now
        contains the LibreDWG path."""
        stale = (
            "# generated_at: 2026-04-23T14:15:24Z\n"
            '"""Handler stub for dwg files."""\n'
            "def read_text(path):\n"
            "    from ezdxf.addons import odafc\n"
            "    return ''\n"
            "def extract_images(path, out_dir):\n"
            "    return []\n"
        )
        wd = _make_workdir_with_handler(tmp_path, "cad_dwg_dwg.py", stale)
        drift = handler_refresh.detect_outdated_handlers(str(wd))
        assert len(drift) == 1

        result = handler_refresh.refresh_handlers(str(wd), drift)
        assert len(result.refreshed) == 1
        assert result.refreshed[0] == ("cad-dwg", "dwg")
        assert result.failed == []

        # The refreshed file now matches the current template.
        post = (wd / ".vault-bridge" / "handlers" / "cad_dwg_dwg.py").read_text()
        assert "_convert_via_libredwg" in post
        post_drift = handler_refresh.detect_outdated_handlers(str(wd))
        assert post_drift == []

    def test_refresh_empty_choices_is_a_no_op(self, tmp_path):
        result = handler_refresh.refresh_handlers(str(tmp_path), [])
        assert result.refreshed == []
        assert result.failed == []
